### ISSUE TITLE
use java 

### ISSUE THREAD

**Issue by Chenshuai770** [MindorksOpenSource/RxJava3-Android-Examples#1]
Can soupout java?

**Comment by mwshubham** [comment]
You can refer to https://github.com/amitshekhariitbhu/RxJava2-Android-Samples for Java sample with RxJava2
RxJava2 and RxJava3 are quite similar. Although I recommend kotlin language as its 4year now since google announced first class support to kotlin language.
Please close if required. cc: @amitshekhariitbhu
